version: '3'

networks:
  petclinic-net-r2:
    driver: bridge

services:
  backend-postgres-12-r2:
    container_name: backend-postgres-12-r2
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB1_PASSWORD}
      POSTGRES_USER: ${DB1_USERNAME}
      POSTGRES_DB: ${DB1_NAME}
    networks:
      - petclinic-net-r2

  petclinic-backend-r2:
    container_name: petclinic-backend-r2
    image: docker.haulmont.com/platform/infrastructure/demo-cuba-apps-docker/demo-r2/amplicode-petclinic-demo-r2:backend
    restart: unless-stopped
    environment:
      RDS_HOSTNAME: backend-postgres-12-r2
      RDS_PASSWORD: ${DB1_PASSWORD}
      RDS_USERNAME: ${DB1_USERNAME}
      RDS_DB_NAME: ${DB1_NAME}
      RDS_PORT: 5432
      SPRING_PROFILES_ACTIVE: docker
      APP_USERS_ADMIN_USERNAME: ${JMIX_ADMIN}
      APP_USERS_ADMIN_PASSWORD: ${JMIX_PASSWORD}
    ports:
      - "8085:8080"
    networks:
      - petclinic-net-r2