version: '3'

networks:
  petclinic-net:
    driver: bridge

services:
  backend-postgres-12:
    container_name: backend-postgres-12
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - petclinic-net

  petclinic-backend:
    container_name: petclinic-backend
    image: docker.haulmont.com/platform/infrastructure/demo-cuba-apps-docker/demo-r2/amplicode-petclinic-demo-r2:backend
    restart: unless-stopped
    environment:
      RDS_HOSTNAME: backend-postgres-12
      RDS_PASSWORD: ${DB_PASSWORD}
      RDS_USERNAME: ${DB_USERNAME}
      RDS_DB_NAME: ${DB_NAME}
      RDS_PORT: 5432
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8080"
    networks:
      - petclinic-net