CREATE TABLE owner
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    city       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255),
    telephone  VARCHAR(255),
    username   VARCHAR(50),
    CONSTRAINT pk_owner PRIMARY KEY (id)
);

create table users
(
    username varchar(50) not null primary key,
    password varchar(500) not null,
    enabled  boolean not null
);

create table authorities
(
    username  varchar(50) not null,
    authority varchar(50) not null,
    constraint fk_authorities_users foreign key (username) references users (username)
);

CREATE TABLE veterinarian
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    username VARCHAR(50),
    CONSTRAINT pk_veterinarian PRIMARY KEY (id)
);

CREATE TABLE pet
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identification_number VARCHAR(255)                            NOT NULL,
    birth_date            date,
    type_id               BIGINT,
    owner_id              BIGINT,
    avatar_url            VARCHAR(255),
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE pet_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pet_type PRIMARY KEY (id)
);

CREATE TABLE visit
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id          BIGINT                                  NOT NULL,
    visit_start     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description     VARCHAR(4000),
    state           VARCHAR(255)                            NOT NULL,
    veterinarian_id BIGINT,
    CONSTRAINT pk_visit PRIMARY KEY (id)
);

CREATE TABLE attachment
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    url      VARCHAR(255),
    visit_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);


ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owner (id);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_TYPE FOREIGN KEY (type_id) REFERENCES pet_type (id);

ALTER TABLE visit
    ADD CONSTRAINT FK_VISIT_ON_PET FOREIGN KEY (pet_id) REFERENCES pet (id);

ALTER TABLE visit
    ADD CONSTRAINT FK_VISIT_ON_VETERINARIAN FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_VISIT FOREIGN KEY (visit_id) REFERENCES visit (id);

ALTER TABLE owner
    ADD CONSTRAINT FK_OWNER_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);

ALTER TABLE veterinarian
    ADD CONSTRAINT FK_VETERINARIAN_ON_USER_USERNAME FOREIGN KEY (username) REFERENCES users (username);

create unique index ix_auth_username on authorities (username, authority);