CREATE TABLE owner
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    city       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255),
    telephone  VARCHAR(255),
    CONSTRAINT pk_owner PRIMARY KEY (id)
);

CREATE TABLE pet
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identification_number VARCHAR(255)                            NOT NULL,
    birth_date            date,
    type_id               BIGINT,
    owner_id              BIGINT,
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE pet_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pet_type PRIMARY KEY (id)
);

CREATE TABLE visit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id      BIGINT                                  NOT NULL,
    visit_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    visit_end   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(4000),
    CONSTRAINT pk_visit PRIMARY KEY (id)
);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owner (id);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_TYPE FOREIGN KEY (type_id) REFERENCES pet_type (id);

ALTER TABLE visit
    ADD CONSTRAINT FK_VISIT_ON_PET FOREIGN KEY (pet_id) REFERENCES pet (id);

CREATE TABLE test_entity
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    string               VARCHAR(255),
    bool                 BOOLEAN,
    double_test          DOUBLE PRECISION,
    int_test             INTEGER,
    long_test            BIGINT,
    big_decimal          DECIMAL(19, 2),
    date                 date,
    time                 TIME WITHOUT TIME ZONE,
    time_stamp           TIMESTAMP WITHOUT TIME ZONE,
    date_util            date,
    uuid_test            UUID,
    byte_test            SMALLINT,
    character            CHAR,
    class_test           VARCHAR(255),
    float_test           FLOAT,
    short_test           SMALLINT,
    big_int              DECIMAL,
    url                  VARCHAR(255),
    blob                 OID,
    clob                 TEXT,
    nclob                TEXT,
    duration             BIGINT,
    instant              TIMESTAMP WITHOUT TIME ZONE,
    local_date           date,
    local_date_time      TIMESTAMP WITHOUT TIME ZONE,
    local_time           TIME WITHOUT TIME ZONE,
    offset_date_time     TIMESTAMP with time zone,
    offset_time          TIME WITH TIME ZONE,
    zoned_date_time      TIMESTAMP with time zone,
    calendar             date,
    currency             VARCHAR(255),
    locale               VARCHAR(255),
    bool_primitive       BOOLEAN,
    byte_primitive       SMALLINT,
    char_primitive       CHAR,
    short_primitive      SMALLINT,
    byte_array           OID,
    char_array           VARCHAR(255),
    byte_primitive_array OID,
    char_primitive_array VARCHAR(255),
    CONSTRAINT pk_test_entity PRIMARY KEY (id)
);
